import { useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { api } from '../services/api'

export default function Dashboard() {
  const { user, loading, logout } = useAuth(); const [cicdStatus, setCicdStatus] = useState('Checking CI/CD deployment...'); const [cicdMessage, setCicdMessage] = useState(''); const [appInfo, setAppInfo] = useState(null); const [appInfoError, setAppInfoError] = useState(false)
  useEffect(() => { if (user) api.cicdTest().then(({ message }) => { setCicdMessage(message); setCicdStatus('CI/CD endpoint reached successfully.') }).catch(() => { setCicdMessage(''); setCicdStatus('CI/CD endpoint could not be reached.') }) }, [user])
  useEffect(() => { if (user) api.appInfo().then(setAppInfo).catch(() => setAppInfoError(true)) }, [user])
  if (loading) return <div className="loading-screen">Loading your account...</div>; if (!user) return <Navigate to="/login" replace />
  return <main className="dashboard"><header className="topbar"><div className="brand-mark">A<span>/</span>O</div><button className="text-button" onClick={logout}>Sign out <span aria-hidden="true">↗</span></button></header><section className="dashboard-content"><p className="eyebrow">Your private space</p><section className="welcome-section" aria-labelledby="welcome-heading"><h1 id="welcome-heading">Welcome back, <em>{user.name}</em>!</h1></section><section className="app-insights" aria-labelledby="app-insights-heading"><div className="app-insights-heading"><span className="detail-label">Backend signal</span><h2 id="app-insights-heading">Application Insights</h2></div>{appInfo ? <div className="app-insights-content"><p>{appInfo.message}</p><div className="app-insights-detail"><span className="detail-label">Environment</span><strong>{appInfo.environment}</strong></div><div className="app-insights-detail"><span className="detail-label">Deployment</span><strong>{appInfo.deployment_message}</strong></div><div className="app-insights-detail"><span className="detail-label">Features</span><ul>{appInfo.features.map((feature) => <li key={feature}>{feature}</li>)}</ul></div></div> : appInfoError && <p className="app-info-error" role="status">Application information is currently unavailable.</p>}</section><div className="account-detail"><span className="detail-label">Account details</span><div><strong>{user.email}</strong><span>Member since {new Date(user.created_at).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</span></div></div><div className="account-detail"><span className="detail-label">Deployment status</span><div><strong>{cicdStatus}</strong>{cicdMessage && <span>{cicdMessage}</span>}</div></div></section></main>
}