name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

concurrency:
  group: backend-production
  cancel-in-progress: false

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout tested commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Create backend artifact
        run: |
          cd backend
          zip -r ../backend.zip . \
            -x ".env" \
            -x ".venv/*" \
            -x "__pycache__/*" \
            -x "*/__pycache__/*" \
            -x ".pytest_cache/*"

      - name: Upload backend artifact
        run: |
          aws s3 cp \
            backend.zip \
            s3://fastapi-deployment-artifacts-123456/releases/backend.zip

      - name: Start Image Builder
        id: image
        run: |
          IMAGE_BUILD_VERSION_ARN=$(aws imagebuilder start-image-pipeline-execution \
            --image-pipeline-arn arn:aws:imagebuilder:ap-south-1:349311508967:image-pipeline/fastapi-backend-pipeline \
            --query 'imageBuildVersionArn' \
            --output text)

          echo "IMAGE_BUILD_VERSION_ARN=$IMAGE_BUILD_VERSION_ARN" >> "$GITHUB_ENV"

          echo "Image build started:"
          echo "$IMAGE_BUILD_VERSION_ARN"

      - name: Wait for Image Builder
        run: |
          for i in {1..60}; do

            STATUS=$(aws imagebuilder get-image \
              --image-build-version-arn "$IMAGE_BUILD_VERSION_ARN" \
              --query 'image.state.status' \
              --output text)

            echo "Image status: $STATUS"

            if [ "$STATUS" = "AVAILABLE" ]; then
              break
            fi

            if [ "$STATUS" = "FAILED" ]; then
              echo "Image Builder failed."
              exit 1
            fi

            sleep 60
          done

          if [ "$STATUS" != "AVAILABLE" ]; then
            echo "Timed out waiting for Image Builder."
            exit 1
          fi

      - name: Get new AMI
        run: |
          AMI_ID=$(aws imagebuilder get-image \
            --image-build-version-arn "$IMAGE_BUILD_VERSION_ARN" \
            --query 'image.outputResources.amis[0].image' \
            --output text)

          echo "AMI_ID=$AMI_ID" >> "$GITHUB_ENV"

          echo "New AMI: $AMI_ID"

      - name: Get current Launch Template version
        run: |
          CURRENT_VERSION=$(aws ec2 describe-launch-template-versions \
            --launch-template-id lt-0a0024fe564174e76 \
            --versions '$Latest' \
            --query 'LaunchTemplateVersions[0].VersionNumber' \
            --output text)

          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_ENV"

      - name: Create new Launch Template version
        run: |
          NEW_VERSION=$(aws ec2 create-launch-template-version \
            --launch-template-id lt-0a0024fe564174e76 \
            --source-version "$CURRENT_VERSION" \
            --version-description "FastAPI deployment ${{ github.event.workflow_run.head_sha }}" \
            --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" \
            --query 'LaunchTemplateVersion.VersionNumber' \
            --output text)

          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"

          echo "New Launch Template version: $NEW_VERSION"

      - name: Update Auto Scaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name fastapi-asg \
            --launch-template \
              "LaunchTemplateName=fastapi-launch-template,Version=$NEW_VERSION"

      - name: Start Instance Refresh
        id: refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name fastapi-asg \
            --preferences \
              MinHealthyPercentage=100,InstanceWarmup=300,SkipMatching=true \
            --query 'InstanceRefreshId' \
            --output text)

          echo "REFRESH_ID=$REFRESH_ID" >> "$GITHUB_ENV"

          echo "Instance Refresh started: $REFRESH_ID"

      - name: Wait for Instance Refresh
        run: |
          for i in {1..60}; do

            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name fastapi-asg \
              --instance-refresh-ids "$REFRESH_ID" \
              --query 'InstanceRefreshes[0].Status' \
              --output text)

            echo "Refresh status: $STATUS"

            if [ "$STATUS" = "Successful" ]; then
              break
            fi

            if [ "$STATUS" = "Failed" ] || \
               [ "$STATUS" = "Cancelled" ] || \
               [ "$STATUS" = "RollbackFailed" ]; then
              echo "Instance Refresh failed."
              exit 1
            fi

            sleep 30
          done

          if [ "$STATUS" != "Successful" ]; then
            echo "Timed out waiting for Instance Refresh."
            exit 1
          fi

      - name: Verify production API
        run: |
          curl --fail --retry 10 --retry-delay 10 \
            https://api.chethanprojectfortrial.store/api/health
